# Generated by Django 2.2.7 on 2019-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('crud_id', models.AutoField(primary_key=True, serialize=False)),
                ('crud_title', models.TextField()),
                ('crud_notification_datetime', models.DateTimeField()),
                ('crud_creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
